crawler:
  # Politeness settings
  respect_robots_txt: true
  user_agent: "WikiaAnalyzer/0.1.0 (+https://github.com/your-repo)"

  # Rate limiting
  default_delay_seconds: 1.0
  max_concurrent_domains: 3
  
  # Request settings  
  timeout_seconds: 30
  max_retries: 3
  retry_delay_seconds: 5
  
  # Content filtering
  max_page_size_mb: 5
  allowed_content_types: 
    - "text/html"
    - "application/xhtml+xml"
  
  # Wikia-specific settings
  target_namespaces:
    - "Main"           # Main articles
    - "Character"      # Character pages
    - "Location"       # Location pages
  
  exclude_patterns:
    - "User:"
    - "User_talk:"
    - "File:"
    - "Category:"
    - "Template:"
    - "Special:"
    - "/wiki/Special:"
    - "/wiki/Category:"
  
  # Session persistence
  save_state_every_n_pages: 10
  auto_resume_on_restart: true