# Domain-specific rate limiting overrides
domains:
  "fandom.com":
    delay_seconds: 2.0
    requests_per_minute: 30
    respect_crawl_delay: true
    
  "wikia.org": 
    delay_seconds: 1.5
    requests_per_minute: 40
    
# Default fallback for unknown domains  
default:
  delay_seconds: 2.0
  requests_per_minute: 30
  max_retries: 3

# Backoff settings
backoff:
  base_delay: 1.0
  max_delay: 300.0
  backoff_factor: 2.0
  jitter: true